### ISSUE TITLE
FileNotFoundException, gurobi90.netstandard20

### ISSUE THREAD

**Issue by jrojer** [merschformann/sardine-can#6]
Hello.

I obtained gurobi dlls, but I cannot figure out where to put them, so the GUI app works in HybridStyle.
Can you please give more info on that?
```
System.IO.FileNotFoundException: 'Could not load file or assembly 'gurobi90.netstandard20, Version=9.0.0.0, Culture=neutral, PublicKeyToken=21e2c4b1860157bc'. The system cannot find the file specified.'
```
I have gurobi90.netstandard20.dll of exact same version 9.0.0.0

**Comment by merschformann** [comment]
I hope this was resolved, if not feel free to re-open.
