### ISSUE TITLE
Stackability is not working

### ISSUE THREAD

**Issue by jrojer** [merschformann/sardine-can#7]
This set up cannot be solved if stackability is forbidden: [stackability_test.zip](https://github.com/merschformann/sardine-can/files/7284447/stackability_test.zip), but the algorithm stacks boxes.

I tested the case for all the solvers and methods (except the ones requiring dlls).

**Comment by merschformann** [comment]
Unfortunately, **the heuristics do not support any kind of gravity** (stacking in the first place or disallowing it). I need to provide some documentation on this. :grimacing: 

You can find many details about the implemented algorithms in the [thesis](https://github.com/merschformann/sardine-can/tree/main/Material/MasterThesis) though. _Table 4.4_ & _Table 5.2_ give an overview of the features supported by the different MIPs and heuristics.

Some notes:
- The MIP models support basic gravity / stacking, but are too slow for real-world problem sizes
- The heuristics are quite fast, but do not respect gravity at all
- The UI was only built for experimentation during my thesis back then and is unfortunately quite confusing about this matter

**Comment by merschformann** [comment]
I hope the answer was satisfactory. :sweat_smile: Feel free to re-open or send me an email, if there are more questions. :relaxed:
